# Generated by Django 4.2 on 2024-12-18 20:43

import chats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='unique_code',
            field=models.CharField(default=chats.models.create_unique_code, max_length=10, verbose_name='Unique code'),
        ),
        migrations.AlterField(
            model_name='member',
            name='chat_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chats.chatgroup', verbose_name='Chat_Group'),
        ),
    ]
