# Generated by Django 4.2 on 2024-12-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chatgroup_unique_code_alter_member_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_activity_msg',
            field=models.BooleanField(default=False, verbose_name='Activity Message'),
        ),
    ]
